# Use OpenJDK 17 as the base image
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app
COPY build/libs/crypto-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENV JAVA_OPTS="-ea -server -Dserver.port=8080"
CMD ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]