/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.svovnenko.crypto.controller;

import com.svovnenko.crypto.domain.dto.CryptoNormalizedRangeListResponseDto;
import com.svovnenko.crypto.domain.dto.CryptoNormalizedRangeResponseDto;
import com.svovnenko.crypto.domain.dto.CryptoStatisticsResponseDto;
import com.svovnenko.crypto.domain.dto.CryptoSymbolDto;
import org.springframework.format.annotation.DateTimeFormat;
import com.svovnenko.crypto.domain.dto.ErrorResponseDto;
import java.time.LocalDate;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-28T10:09:14.407956400+01:00[Europe/Budapest]", comments = "Generator version: 7.17.0")
@Validated
@Controller
@Tag(name = "crypto", description = "the crypto API")
public interface CryptoApi {

    String PATH_HIGHEST_NORMALIZED_RANGE_GET = "/highest-normalized-range";
    /**
     * GET /highest-normalized-range : Get crypto with highest normalized range for a specific day
     * Returns the crypto with the highest normalized range for the specified day and optional time range. For data only for one day start and end dates should be the same
     *
     * @param from Start date (yyyy-MM-dd) (required)
     * @param to End date (yyyy-MM-dd) (optional)
     * @return Crypto with highest normalized range for the day (status code 200)
     *         or Bad request (invalid parameters or date format) (status code 400)
     *         or No crypto found for the specified day (status code 404)
     *         or Service unavailable (server error) (status code 503)
     */
    @Operation(
        operationId = "highestNormalizedRangeGet",
        summary = "Get crypto with highest normalized range for a specific day",
        description = "Returns the crypto with the highest normalized range for the specified day and optional time range. For data only for one day start and end dates should be the same",
        tags = { "crypto" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Crypto with highest normalized range for the day", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CryptoNormalizedRangeResponseDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request (invalid parameters or date format)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "No crypto found for the specified day", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service unavailable (server error)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CryptoApi.PATH_HIGHEST_NORMALIZED_RANGE_GET,
        produces = { "application/json" }
    )
    ResponseEntity<CryptoNormalizedRangeResponseDto> highestNormalizedRangeGet(
        @NotNull @Parameter(name = "from", description = "Start date (yyyy-MM-dd)", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate from,
        @Parameter(name = "to", description = "End date (yyyy-MM-dd)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate to
    );


    String PATH_NORMALIZED_RANGE_GET = "/normalized-range";
    /**
     * GET /normalized-range : Get all cryptos sorted by normalized range
     * Returns a descending sorted list of all cryptos, comparing the normalized range ((max-min)/min) for the specified time range.
     *
     * @param from Start date (yyyy-MM-dd) (optional)
     * @param to End date (yyyy-MM-dd) (optional)
     * @return List of cryptos sorted by normalized range (status code 200)
     *         or Bad request (invalid parameters or date format) (status code 400)
     *         or Service unavailable (server error) (status code 503)
     */
    @Operation(
        operationId = "normalizedRangeGet",
        summary = "Get all cryptos sorted by normalized range",
        description = "Returns a descending sorted list of all cryptos, comparing the normalized range ((max-min)/min) for the specified time range.",
        tags = { "crypto" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of cryptos sorted by normalized range", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CryptoNormalizedRangeListResponseDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request (invalid parameters or date format)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service unavailable (server error)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CryptoApi.PATH_NORMALIZED_RANGE_GET,
        produces = { "application/json" }
    )
    ResponseEntity<CryptoNormalizedRangeListResponseDto> normalizedRangeGet(
        @Parameter(name = "from", description = "Start date (yyyy-MM-dd)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate from,
        @Parameter(name = "to", description = "End date (yyyy-MM-dd)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate to
    );


    String PATH_SYMBOL_STATISTICS_GET = "/{symbol}/statistics";
    /**
     * GET /{symbol}/statistics : Get statistics for a specific crypto
     * Returns oldest, newest, min, and max values for the requested crypto within the specified time range.
     *
     * @param symbol Crypto symbol (required)
     * @param from Start date (yyyy-MM-dd) (optional)
     * @param to End date (yyyy-MM-dd) (optional)
     * @return Statistics for the requested crypto (status code 200)
     *         or Bad request (invalid parameters or date format) (status code 400)
     *         or Crypto not found (status code 404)
     *         or Service unavailable (server error) (status code 503)
     */
    @Operation(
        operationId = "symbolStatisticsGet",
        summary = "Get statistics for a specific crypto",
        description = "Returns oldest, newest, min, and max values for the requested crypto within the specified time range.",
        tags = { "crypto" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Statistics for the requested crypto", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CryptoStatisticsResponseDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request (invalid parameters or date format)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Crypto not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service unavailable (server error)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CryptoApi.PATH_SYMBOL_STATISTICS_GET,
        produces = { "application/json" }
    )
    ResponseEntity<CryptoStatisticsResponseDto> symbolStatisticsGet(
        @NotNull @Parameter(name = "symbol", description = "Crypto symbol", required = true, in = ParameterIn.PATH) @PathVariable("symbol") CryptoSymbolDto symbol,
        @Parameter(name = "from", description = "Start date (yyyy-MM-dd)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate from,
        @Parameter(name = "to", description = "End date (yyyy-MM-dd)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @Nullable LocalDate to
    );

}
